name: craft-integration-test-plugin
version: "1.0"
author: Reecepbcups
main: sh.reece.testingintegration.Main
description: Testing blockchain integration
api-version: 1.17
api: ""

# Must use Paper Spigot!
depend: ["craft-integration"]

commands:
  test-balanceapi:
    description: test to get balance
    usage: /<command>

  test-walletapi:
    description: test to get a users wallet
    usage: /<command>

  test-exampleapi:
    description: creates a transaction for the main plugin (/wallet pending)
    usage: /<command>

  test-tokensapi:
    description: gives tokens (console only)
    usage: /<command>

  test-trade:
    description: fake trade a player + send CRAFT
    usage: /<command>

  test-keplr:
    description: send keplr link to setup
    usage: /<command>

  test-escrowspend:
    description: send keplr link to setup
    usage: /<command>  

  test-craftusd:
    description: get usd price of craft
    usage: /<command>  

  test-expire:
    description: expires a tx & then runs the logic for it after 1 min
    usage: /<command>  