// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: craft/exp/v1beta1/daoinfo.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ModuleAccount defines an account for modules that holds coins on a pool.
type AccountRecord struct {
	Account  string      `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	MaxToken *types.Coin `protobuf:"bytes,2,opt,name=max_token,json=maxToken,proto3" json:"max_token,omitempty"`
}

func (m *AccountRecord) Reset()         { *m = AccountRecord{} }
func (m *AccountRecord) String() string { return proto.CompactTextString(m) }
func (*AccountRecord) ProtoMessage()    {}
func (*AccountRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb2da1562060605, []int{0}
}
func (m *AccountRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRecord.Merge(m, src)
}
func (m *AccountRecord) XXX_Size() int {
	return m.Size()
}
func (m *AccountRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRecord proto.InternalMessageInfo

func (m *AccountRecord) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountRecord) GetMaxToken() *types.Coin {
	if m != nil {
		return m.MaxToken
	}
	return nil
}

type DaoInfo struct {
	DaoAccount string           `protobuf:"bytes,1,opt,name=dao_account,json=daoAccount,proto3" json:"dao_account,omitempty"`
	Whitelist  []*AccountRecord `protobuf:"bytes,2,rep,name=whitelist,proto3" json:"whitelist,omitempty" yaml:"dao_info"`
}

func (m *DaoInfo) Reset()         { *m = DaoInfo{} }
func (m *DaoInfo) String() string { return proto.CompactTextString(m) }
func (*DaoInfo) ProtoMessage()    {}
func (*DaoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fb2da1562060605, []int{1}
}
func (m *DaoInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DaoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DaoInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DaoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DaoInfo.Merge(m, src)
}
func (m *DaoInfo) XXX_Size() int {
	return m.Size()
}
func (m *DaoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DaoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DaoInfo proto.InternalMessageInfo

func (m *DaoInfo) GetDaoAccount() string {
	if m != nil {
		return m.DaoAccount
	}
	return ""
}

func (m *DaoInfo) GetWhitelist() []*AccountRecord {
	if m != nil {
		return m.Whitelist
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountRecord)(nil), "craft.exp.v1beta1.AccountRecord")
	proto.RegisterType((*DaoInfo)(nil), "craft.exp.v1beta1.DaoInfo")
}

func init() { proto.RegisterFile("craft/exp/v1beta1/daoinfo.proto", fileDescriptor_9fb2da1562060605) }

var fileDescriptor_9fb2da1562060605 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xeb, 0xfe, 0xd2, 0xdf, 0xd6, 0x11, 0x42, 0x04, 0x86, 0xb4, 0x83, 0x13, 0x45, 0x42,
	0xea, 0x64, 0xab, 0x45, 0x62, 0xe8, 0x46, 0x61, 0x61, 0x0d, 0x4c, 0x2c, 0x95, 0x93, 0x38, 0x21,
	0x6a, 0xe3, 0x1b, 0x35, 0x2e, 0xa4, 0x13, 0x2b, 0x23, 0x23, 0x63, 0x1f, 0x87, 0xb1, 0x23, 0x13,
	0x42, 0xed, 0x1b, 0xf0, 0x04, 0x28, 0x71, 0x0a, 0xaa, 0xd8, 0x7c, 0xcf, 0x3d, 0x3e, 0xfe, 0x74,
	0x8c, 0xed, 0x60, 0xce, 0x23, 0xc5, 0x44, 0x91, 0xb1, 0x87, 0x81, 0x2f, 0x14, 0x1f, 0xb0, 0x90,
	0x43, 0x22, 0x23, 0xa0, 0xd9, 0x1c, 0x14, 0x98, 0x47, 0x95, 0x81, 0x8a, 0x22, 0xa3, 0xb5, 0xa1,
	0xd7, 0x0d, 0x20, 0x4f, 0x21, 0x9f, 0x54, 0x06, 0xa6, 0x07, 0xed, 0xee, 0x9d, 0xc4, 0x10, 0x83,
	0xd6, 0xcb, 0x53, 0xad, 0x76, 0x63, 0x80, 0x78, 0x26, 0x58, 0x35, 0xf9, 0x8b, 0x88, 0x71, 0xb9,
	0xac, 0x57, 0x44, 0x5f, 0x67, 0x3e, 0xcf, 0xc5, 0x0f, 0x41, 0x00, 0x89, 0xd4, 0x7b, 0x77, 0x8a,
	0x0f, 0x2e, 0x82, 0x00, 0x16, 0x52, 0x79, 0x22, 0x80, 0x79, 0x68, 0x5a, 0xb8, 0xc5, 0xb5, 0x60,
	0x21, 0x07, 0xf5, 0x3b, 0xde, 0x6e, 0x34, 0xcf, 0x71, 0x27, 0xe5, 0xc5, 0x44, 0xc1, 0x54, 0x48,
	0xab, 0xe9, 0xa0, 0xbe, 0x31, 0xec, 0xd2, 0x9a, 0xae, 0x8c, 0xdf, 0xf1, 0xd3, 0x4b, 0x48, 0xa4,
	0xd7, 0x4e, 0x79, 0x71, 0x5b, 0x5a, 0x47, 0xed, 0xe7, 0x95, 0x8d, 0x5e, 0x57, 0x36, 0x72, 0x9f,
	0x70, 0xeb, 0x8a, 0xc3, 0xb5, 0x8c, 0xc0, 0xb4, 0xb1, 0x11, 0x72, 0x98, 0xec, 0x3f, 0x85, 0x43,
	0x0e, 0x35, 0x8d, 0x79, 0x83, 0x3b, 0x8f, 0xf7, 0x89, 0x12, 0xb3, 0x24, 0x57, 0x56, 0xd3, 0xf9,
	0xd7, 0x37, 0x86, 0x0e, 0xfd, 0xd3, 0x15, 0xdd, 0x83, 0x1f, 0x1f, 0x7f, 0x7d, 0xd8, 0x87, 0x4b,
	0x9e, 0xce, 0x46, 0x6e, 0x99, 0x5e, 0xd6, 0xec, 0x7a, 0xbf, 0x39, 0xe3, 0xd3, 0xb7, 0x0d, 0x41,
	0xeb, 0x0d, 0x41, 0x9f, 0x1b, 0x82, 0x5e, 0xb6, 0xa4, 0xb1, 0xde, 0x92, 0xc6, 0xfb, 0x96, 0x34,
	0xee, 0x8c, 0xa2, 0xfa, 0x23, 0xb5, 0xcc, 0x44, 0xee, 0xff, 0xaf, 0xba, 0x39, 0xfb, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xef, 0xd3, 0xdd, 0x19, 0xbd, 0x01, 0x00, 0x00,
}

func (m *AccountRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxToken != nil {
		{
			size, err := m.MaxToken.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDaoinfo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintDaoinfo(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DaoInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DaoInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DaoInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Whitelist) > 0 {
		for iNdEx := len(m.Whitelist) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Whitelist[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDaoinfo(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.DaoAccount) > 0 {
		i -= len(m.DaoAccount)
		copy(dAtA[i:], m.DaoAccount)
		i = encodeVarintDaoinfo(dAtA, i, uint64(len(m.DaoAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDaoinfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovDaoinfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AccountRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovDaoinfo(uint64(l))
	}
	if m.MaxToken != nil {
		l = m.MaxToken.Size()
		n += 1 + l + sovDaoinfo(uint64(l))
	}
	return n
}

func (m *DaoInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DaoAccount)
	if l > 0 {
		n += 1 + l + sovDaoinfo(uint64(l))
	}
	if len(m.Whitelist) > 0 {
		for _, e := range m.Whitelist {
			l = e.Size()
			n += 1 + l + sovDaoinfo(uint64(l))
		}
	}
	return n
}

func sovDaoinfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDaoinfo(x uint64) (n int) {
	return sovDaoinfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccountRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaoinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaoinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaoinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaoinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaoinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDaoinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDaoinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MaxToken == nil {
				m.MaxToken = &types.Coin{}
			}
			if err := m.MaxToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDaoinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaoinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DaoInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaoinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DaoInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DaoInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaoinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaoinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaoinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DaoAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaoinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDaoinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDaoinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Whitelist = append(m.Whitelist, &AccountRecord{})
			if err := m.Whitelist[len(m.Whitelist)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDaoinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaoinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDaoinfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDaoinfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDaoinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDaoinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDaoinfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDaoinfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDaoinfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDaoinfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDaoinfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDaoinfo = fmt.Errorf("proto: unexpected end of group")
)
