// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: craft/exp/v1beta1/exp_request.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RequestStatus int32

const (
	// REQUEST_STATUS_COMPLETE defines a request status completed.
	StatusCompleteRequest RequestStatus = 0
	// REQUEST_STATUS_PERIOD defines a request status current in process
	StatusOnGoingRequest RequestStatus = 1
	// REQUEST_STATUS_EXPIRED defines the expired request status.
	StatusExpiredRequest RequestStatus = 2
	// REQUEST_STATUS_EXPIRED defines the request status that member don't fund to exp module.
	StatusNoFundRequest RequestStatus = 3
)

var RequestStatus_name = map[int32]string{
	0: "StatusCompleteRequest",
	1: "StatusOnGoingRequest",
	2: "StatusExpiredRequest",
	3: "StatusNoFundRequest",
}

var RequestStatus_value = map[string]int32{
	"StatusCompleteRequest": 0,
	"StatusOnGoingRequest":  1,
	"StatusExpiredRequest":  2,
	"StatusNoFundRequest":   3,
}

func (x RequestStatus) String() string {
	return proto.EnumName(RequestStatus_name, int32(x))
}

func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_94f58b9d8d17be18, []int{0}
}

type BurnRequest struct {
	Account       string        `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	BurnTokenLeft *types.Coin   `protobuf:"bytes,2,opt,name=burn_token_left,json=burnTokenLeft,proto3" json:"burn_token_left,omitempty"`
	RequestTime   time.Time     `protobuf:"bytes,3,opt,name=request_time,json=requestTime,proto3,stdtime" json:"request_time"`
	Status        RequestStatus `protobuf:"varint,4,opt,name=status,proto3,enum=craft.exp.v1beta1.RequestStatus" json:"status,omitempty"`
}

func (m *BurnRequest) Reset()         { *m = BurnRequest{} }
func (m *BurnRequest) String() string { return proto.CompactTextString(m) }
func (*BurnRequest) ProtoMessage()    {}
func (*BurnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94f58b9d8d17be18, []int{0}
}
func (m *BurnRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BurnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BurnRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BurnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurnRequest.Merge(m, src)
}
func (m *BurnRequest) XXX_Size() int {
	return m.Size()
}
func (m *BurnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BurnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BurnRequest proto.InternalMessageInfo

func (m *BurnRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BurnRequest) GetBurnTokenLeft() *types.Coin {
	if m != nil {
		return m.BurnTokenLeft
	}
	return nil
}

func (m *BurnRequest) GetRequestTime() time.Time {
	if m != nil {
		return m.RequestTime
	}
	return time.Time{}
}

func (m *BurnRequest) GetStatus() RequestStatus {
	if m != nil {
		return m.Status
	}
	return StatusCompleteRequest
}

type MintRequest struct {
	Account        string                                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	DaoTokenMinted github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=dao_token_minted,json=daoTokenMinted,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"dao_token_minted" yaml:"dao_token_mint"`
	DaoTokenLeft   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=dao_token_left,json=daoTokenLeft,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"dao_token_left" yaml:"dao_token_left"`
	RequestTime    time.Time                              `protobuf:"bytes,4,opt,name=RequestTime,proto3,stdtime" json:"RequestTime"`
	Status         RequestStatus                          `protobuf:"varint,5,opt,name=status,proto3,enum=craft.exp.v1beta1.RequestStatus" json:"status,omitempty"`
}

func (m *MintRequest) Reset()         { *m = MintRequest{} }
func (m *MintRequest) String() string { return proto.CompactTextString(m) }
func (*MintRequest) ProtoMessage()    {}
func (*MintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94f58b9d8d17be18, []int{1}
}
func (m *MintRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintRequest.Merge(m, src)
}
func (m *MintRequest) XXX_Size() int {
	return m.Size()
}
func (m *MintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MintRequest proto.InternalMessageInfo

func (m *MintRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MintRequest) GetRequestTime() time.Time {
	if m != nil {
		return m.RequestTime
	}
	return time.Time{}
}

func (m *MintRequest) GetStatus() RequestStatus {
	if m != nil {
		return m.Status
	}
	return StatusCompleteRequest
}

type OracleRequest struct {
	Client_ID       uint64                                  `protobuf:"varint,1,opt,name=client_ID,json=clientID,proto3" json:"client_ID,omitempty"`
	Type            string                                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AddressRequest  string                                  `protobuf:"bytes,3,opt,name=address_request,json=addressRequest,proto3" json:"address_request,omitempty"`
	AmountInRequest github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,4,opt,name=amount_in_request,json=amountInRequest,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"amount_in_request" yaml:"amount_in_request"`
}

func (m *OracleRequest) Reset()         { *m = OracleRequest{} }
func (m *OracleRequest) String() string { return proto.CompactTextString(m) }
func (*OracleRequest) ProtoMessage()    {}
func (*OracleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94f58b9d8d17be18, []int{2}
}
func (m *OracleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleRequest.Merge(m, src)
}
func (m *OracleRequest) XXX_Size() int {
	return m.Size()
}
func (m *OracleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OracleRequest proto.InternalMessageInfo

func (m *OracleRequest) GetClient_ID() uint64 {
	if m != nil {
		return m.Client_ID
	}
	return 0
}

func (m *OracleRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OracleRequest) GetAddressRequest() string {
	if m != nil {
		return m.AddressRequest
	}
	return ""
}

func init() {
	proto.RegisterEnum("craft.exp.v1beta1.RequestStatus", RequestStatus_name, RequestStatus_value)
	proto.RegisterType((*BurnRequest)(nil), "craft.exp.v1beta1.BurnRequest")
	proto.RegisterType((*MintRequest)(nil), "craft.exp.v1beta1.MintRequest")
	proto.RegisterType((*OracleRequest)(nil), "craft.exp.v1beta1.OracleRequest")
}

func init() {
	proto.RegisterFile("craft/exp/v1beta1/exp_request.proto", fileDescriptor_94f58b9d8d17be18)
}

var fileDescriptor_94f58b9d8d17be18 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xbd, 0x4f, 0x14, 0x4d,
	0x18, 0xbf, 0xe1, 0xee, 0xe5, 0x85, 0x39, 0x38, 0x60, 0x85, 0xb8, 0x9c, 0xc9, 0xee, 0xe5, 0x8c,
	0x42, 0x4c, 0xdc, 0x0d, 0xd8, 0x18, 0x3a, 0x0f, 0x84, 0x10, 0x45, 0x92, 0x91, 0xca, 0x66, 0x33,
	0xb7, 0x3b, 0x77, 0x6e, 0xd8, 0x9d, 0x59, 0x76, 0x67, 0xf5, 0x28, 0xec, 0x29, 0x69, 0x4c, 0x2c,
	0x49, 0xfc, 0x67, 0x28, 0x29, 0x8d, 0xc5, 0x69, 0xa0, 0xb5, 0xa2, 0xb1, 0x35, 0xf3, 0xc5, 0x85,
	0x60, 0x22, 0x31, 0x56, 0x37, 0xf3, 0x3c, 0xbf, 0x79, 0xe6, 0xf7, 0xb1, 0x73, 0xf0, 0x7e, 0x98,
	0xe3, 0x1e, 0xf7, 0xc9, 0x20, 0xf3, 0xdf, 0xad, 0x74, 0x09, 0xc7, 0x2b, 0x62, 0x1d, 0xe4, 0xe4,
	0xa0, 0x24, 0x05, 0xf7, 0xb2, 0x9c, 0x71, 0x66, 0xcd, 0x49, 0x90, 0x47, 0x06, 0x99, 0xa7, 0x41,
	0xcd, 0xc5, 0x90, 0x15, 0x29, 0x2b, 0x02, 0x09, 0xf0, 0xd5, 0x46, 0xa1, 0x9b, 0xf3, 0x7d, 0xd6,
	0x67, 0xaa, 0x2e, 0x56, 0xba, 0xea, 0x28, 0x8c, 0xdf, 0xc5, 0x05, 0xb9, 0xba, 0x2a, 0x64, 0x31,
	0xd5, 0x7d, 0xb7, 0xcf, 0x58, 0x3f, 0x21, 0xbe, 0xdc, 0x75, 0xcb, 0x9e, 0xcf, 0xe3, 0x94, 0x14,
	0x1c, 0xa7, 0x99, 0x02, 0xb4, 0x7f, 0x02, 0x58, 0xef, 0x94, 0x39, 0x45, 0x8a, 0x9a, 0x65, 0xc3,
	0xff, 0x71, 0x18, 0xb2, 0x92, 0x72, 0x1b, 0xb4, 0xc0, 0xf2, 0x24, 0x32, 0x5b, 0xeb, 0x19, 0x9c,
	0xe9, 0x96, 0x39, 0x0d, 0x38, 0xdb, 0x27, 0x34, 0x48, 0x48, 0x8f, 0xdb, 0x63, 0x2d, 0xb0, 0x5c,
	0x5f, 0x5d, 0xf4, 0x34, 0x51, 0x41, 0xc2, 0x48, 0xf1, 0xd6, 0x59, 0x4c, 0xd1, 0xb4, 0x38, 0xb1,
	0x27, 0x0e, 0xbc, 0x24, 0x3d, 0x6e, 0x6d, 0xc1, 0x29, 0x6d, 0x41, 0x20, 0x78, 0xd8, 0x55, 0x79,
	0xbe, 0xe9, 0x29, 0x92, 0x9e, 0x21, 0xe9, 0xed, 0x19, 0x92, 0x9d, 0x89, 0xd3, 0xa1, 0x5b, 0x39,
	0xfe, 0xe6, 0x02, 0x54, 0xd7, 0x27, 0x45, 0xcf, 0x7a, 0x0a, 0xc7, 0x0b, 0x8e, 0x79, 0x59, 0xd8,
	0xb5, 0x16, 0x58, 0x6e, 0xac, 0xb6, 0xbc, 0x1b, 0x5e, 0x7a, 0x5a, 0xd1, 0x6b, 0x89, 0x43, 0x1a,
	0xbf, 0x36, 0x71, 0x74, 0xe2, 0x82, 0x4f, 0x27, 0x2e, 0x68, 0x7f, 0xac, 0xc2, 0xfa, 0x4e, 0x4c,
	0xf9, 0x9f, 0x95, 0x1f, 0xc0, 0xd9, 0x08, 0x33, 0x2d, 0x3c, 0x8d, 0x29, 0x27, 0x91, 0x94, 0x3e,
	0xd9, 0xd9, 0x12, 0xf4, 0xbe, 0x0e, 0xdd, 0x87, 0xfd, 0x98, 0xbf, 0x2d, 0xbb, 0x5e, 0xc8, 0x52,
	0x9d, 0x9a, 0xfe, 0x79, 0x5c, 0x44, 0xfb, 0x3e, 0x3f, 0xcc, 0x48, 0xe1, 0x6d, 0x90, 0xf0, 0x72,
	0xe8, 0x2e, 0x1c, 0xe2, 0x34, 0x59, 0x6b, 0x5f, 0x9f, 0xd7, 0x46, 0x8d, 0x08, 0x33, 0xe9, 0xd3,
	0x8e, 0x1c, 0x6f, 0xa5, 0xb0, 0x31, 0x82, 0x48, 0xaf, 0xab, 0xff, 0xea, 0x42, 0x31, 0xad, 0x8d,
	0xa6, 0xcc, 0x85, 0x32, 0x98, 0x4d, 0x58, 0x47, 0x23, 0x7b, 0xa5, 0xa9, 0xb7, 0xce, 0x05, 0xfd,
	0x36, 0x97, 0xff, 0xfe, 0x3a, 0x97, 0x1f, 0x00, 0x4e, 0xef, 0xe6, 0x38, 0x4c, 0x88, 0x49, 0xe6,
	0x1e, 0x9c, 0x0c, 0x93, 0x98, 0x50, 0x1e, 0x6c, 0x6f, 0xc8, 0x6c, 0x6a, 0x68, 0x42, 0x15, 0xb6,
	0x37, 0x2c, 0x0b, 0xd6, 0x84, 0x5c, 0x15, 0x08, 0x92, 0x6b, 0x6b, 0x09, 0xce, 0xe0, 0x28, 0xca,
	0x49, 0x51, 0x98, 0x27, 0xa7, 0xec, 0x43, 0x0d, 0x5d, 0x36, 0x93, 0xdf, 0xc3, 0x39, 0x9c, 0x8a,
	0x8c, 0x83, 0x98, 0x5e, 0x41, 0x6b, 0xd2, 0xe9, 0x17, 0xda, 0xe9, 0xa5, 0x5b, 0x38, 0x2d, 0xbe,
	0xf5, 0xcb, 0xa1, 0x6b, 0x2b, 0xab, 0x6f, 0x4c, 0x6c, 0xa3, 0x19, 0x55, 0xdb, 0x36, 0xcf, 0x6c,
	0x24, 0xf7, 0xd1, 0x07, 0x38, 0x7d, 0xcd, 0x11, 0x6b, 0x11, 0x2e, 0xa8, 0xd5, 0x3a, 0x4b, 0xb3,
	0x84, 0x70, 0x63, 0xc3, 0x6c, 0xc5, 0xb2, 0xe1, 0xbc, 0x6a, 0xed, 0xd2, 0x2d, 0x16, 0xd3, 0xbe,
	0xe9, 0x80, 0x51, 0xe7, 0xf9, 0x20, 0x8b, 0x73, 0x12, 0x99, 0xce, 0x98, 0x75, 0x17, 0xde, 0x51,
	0x9d, 0x57, 0x6c, 0xb3, 0xa4, 0x57, 0x8d, 0x6a, 0xb3, 0x76, 0xf4, 0xd9, 0xa9, 0x74, 0x1e, 0x9c,
	0x9e, 0x3b, 0xe0, 0xec, 0xdc, 0x01, 0xdf, 0xcf, 0x1d, 0x70, 0x7c, 0xe1, 0x54, 0xce, 0x2e, 0x9c,
	0xca, 0x97, 0x0b, 0xa7, 0xf2, 0xa6, 0x3e, 0x90, 0xff, 0x5f, 0x52, 0x61, 0x77, 0x5c, 0x7e, 0x03,
	0x4f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x36, 0x7e, 0x47, 0xf7, 0xd9, 0x04, 0x00, 0x00,
}

func (m *BurnRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BurnRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BurnRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintExpRequest(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.RequestTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.RequestTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintExpRequest(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	if m.BurnTokenLeft != nil {
		{
			size, err := m.BurnTokenLeft.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintExpRequest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintExpRequest(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MintRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintExpRequest(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.RequestTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.RequestTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintExpRequest(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x22
	{
		size := m.DaoTokenLeft.Size()
		i -= size
		if _, err := m.DaoTokenLeft.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintExpRequest(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.DaoTokenMinted.Size()
		i -= size
		if _, err := m.DaoTokenMinted.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintExpRequest(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintExpRequest(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OracleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AmountInRequest.Size()
		i -= size
		if _, err := m.AmountInRequest.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintExpRequest(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.AddressRequest) > 0 {
		i -= len(m.AddressRequest)
		copy(dAtA[i:], m.AddressRequest)
		i = encodeVarintExpRequest(dAtA, i, uint64(len(m.AddressRequest)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintExpRequest(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x12
	}
	if m.Client_ID != 0 {
		i = encodeVarintExpRequest(dAtA, i, uint64(m.Client_ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintExpRequest(dAtA []byte, offset int, v uint64) int {
	offset -= sovExpRequest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BurnRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovExpRequest(uint64(l))
	}
	if m.BurnTokenLeft != nil {
		l = m.BurnTokenLeft.Size()
		n += 1 + l + sovExpRequest(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.RequestTime)
	n += 1 + l + sovExpRequest(uint64(l))
	if m.Status != 0 {
		n += 1 + sovExpRequest(uint64(m.Status))
	}
	return n
}

func (m *MintRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovExpRequest(uint64(l))
	}
	l = m.DaoTokenMinted.Size()
	n += 1 + l + sovExpRequest(uint64(l))
	l = m.DaoTokenLeft.Size()
	n += 1 + l + sovExpRequest(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.RequestTime)
	n += 1 + l + sovExpRequest(uint64(l))
	if m.Status != 0 {
		n += 1 + sovExpRequest(uint64(m.Status))
	}
	return n
}

func (m *OracleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Client_ID != 0 {
		n += 1 + sovExpRequest(uint64(m.Client_ID))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovExpRequest(uint64(l))
	}
	l = len(m.AddressRequest)
	if l > 0 {
		n += 1 + l + sovExpRequest(uint64(l))
	}
	l = m.AmountInRequest.Size()
	n += 1 + l + sovExpRequest(uint64(l))
	return n
}

func sovExpRequest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozExpRequest(x uint64) (n int) {
	return sovExpRequest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BurnRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExpRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BurnRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BurnRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnTokenLeft", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BurnTokenLeft == nil {
				m.BurnTokenLeft = &types.Coin{}
			}
			if err := m.BurnTokenLeft.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.RequestTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RequestStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipExpRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExpRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MintRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExpRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoTokenMinted", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DaoTokenMinted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoTokenLeft", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DaoTokenLeft.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.RequestTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RequestStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipExpRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExpRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExpRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Client_ID", wireType)
			}
			m.Client_ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Client_ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressRequest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressRequest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountInRequest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountInRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExpRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExpRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExpRequest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExpRequest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExpRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExpRequest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupExpRequest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthExpRequest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthExpRequest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExpRequest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupExpRequest = fmt.Errorf("proto: unexpected end of group")
)
