// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: craft/exp/v1beta1/expstack.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ModuleAccount defines an account for modules that holds coins on a pool.
type BurnRequest struct {
	Account  string      `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	MaxToken *types.Coin `protobuf:"bytes,2,opt,name=max_token,json=maxToken,proto3" json:"max_token,omitempty"`
}

func (m *BurnRequest) Reset()         { *m = BurnRequest{} }
func (m *BurnRequest) String() string { return proto.CompactTextString(m) }
func (*BurnRequest) ProtoMessage()    {}
func (*BurnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644661324da98abd, []int{0}
}
func (m *BurnRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BurnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BurnRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BurnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurnRequest.Merge(m, src)
}
func (m *BurnRequest) XXX_Size() int {
	return m.Size()
}
func (m *BurnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BurnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BurnRequest proto.InternalMessageInfo

func (m *BurnRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BurnRequest) GetMaxToken() *types.Coin {
	if m != nil {
		return m.MaxToken
	}
	return nil
}

type MintRequest struct {
	Account  string      `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	MaxToken *types.Coin `protobuf:"bytes,2,opt,name=max_token,json=maxToken,proto3" json:"max_token,omitempty"`
}

func (m *MintRequest) Reset()         { *m = MintRequest{} }
func (m *MintRequest) String() string { return proto.CompactTextString(m) }
func (*MintRequest) ProtoMessage()    {}
func (*MintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_644661324da98abd, []int{1}
}
func (m *MintRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintRequest.Merge(m, src)
}
func (m *MintRequest) XXX_Size() int {
	return m.Size()
}
func (m *MintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MintRequest proto.InternalMessageInfo

func (m *MintRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MintRequest) GetMaxToken() *types.Coin {
	if m != nil {
		return m.MaxToken
	}
	return nil
}

type RequestList struct {
	MintRequestList []*MintRequest `protobuf:"bytes,1,rep,name=mint_request_list,json=mintRequestList,proto3" json:"mint_request_list,omitempty" yaml:"mint_request_list"`
	BurnRequestList []*BurnRequest `protobuf:"bytes,2,rep,name=burn_request_list,json=burnRequestList,proto3" json:"burn_request_list,omitempty" yaml:"burn_request_list"`
}

func (m *RequestList) Reset()         { *m = RequestList{} }
func (m *RequestList) String() string { return proto.CompactTextString(m) }
func (*RequestList) ProtoMessage()    {}
func (*RequestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_644661324da98abd, []int{2}
}
func (m *RequestList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestList.Merge(m, src)
}
func (m *RequestList) XXX_Size() int {
	return m.Size()
}
func (m *RequestList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestList proto.InternalMessageInfo

func (m *RequestList) GetMintRequestList() []*MintRequest {
	if m != nil {
		return m.MintRequestList
	}
	return nil
}

func (m *RequestList) GetBurnRequestList() []*BurnRequest {
	if m != nil {
		return m.BurnRequestList
	}
	return nil
}

func init() {
	proto.RegisterType((*BurnRequest)(nil), "craft.exp.v1beta1.BurnRequest")
	proto.RegisterType((*MintRequest)(nil), "craft.exp.v1beta1.MintRequest")
	proto.RegisterType((*RequestList)(nil), "craft.exp.v1beta1.RequestList")
}

func init() { proto.RegisterFile("craft/exp/v1beta1/expstack.proto", fileDescriptor_644661324da98abd) }

var fileDescriptor_644661324da98abd = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x40, 0xeb, 0x22, 0x41, 0x9b, 0x0c, 0x55, 0x23, 0x86, 0xb4, 0x42, 0x4e, 0x15, 0x09, 0xa9,
	0x93, 0xa3, 0x16, 0x89, 0xa1, 0x63, 0x59, 0x61, 0x89, 0x98, 0x58, 0x22, 0x27, 0x72, 0x83, 0xd5,
	0xda, 0x0e, 0xb1, 0x83, 0xd2, 0x3f, 0x60, 0x64, 0x64, 0xec, 0xe7, 0x30, 0x76, 0x64, 0x42, 0xd0,
	0xfe, 0x01, 0x5f, 0x80, 0x9c, 0xa4, 0xb4, 0x28, 0x62, 0x65, 0xbb, 0x3b, 0x3f, 0xdd, 0x3b, 0xfb,
	0x6c, 0x0c, 0xa2, 0x14, 0xcf, 0x94, 0x47, 0xf2, 0xc4, 0x7b, 0x1c, 0x85, 0x44, 0xe1, 0x91, 0x8e,
	0xa5, 0xc2, 0xd1, 0x1c, 0x25, 0xa9, 0x50, 0xc2, 0xea, 0x16, 0x04, 0x22, 0x79, 0x82, 0x2a, 0xa2,
	0xdf, 0x8b, 0x84, 0x64, 0x42, 0x06, 0x05, 0xe0, 0x95, 0x49, 0x49, 0xf7, 0x4f, 0x63, 0x11, 0x8b,
	0xb2, 0xae, 0xa3, 0xaa, 0x0a, 0x4b, 0xc6, 0x0b, 0xb1, 0x24, 0x3f, 0x9e, 0x48, 0x50, 0x5e, 0x9d,
	0x3b, 0xb1, 0x10, 0xf1, 0x82, 0x78, 0x45, 0x16, 0x66, 0x33, 0x4f, 0x51, 0x46, 0xa4, 0xc2, 0x2c,
	0x29, 0x01, 0x97, 0x1a, 0xe6, 0x34, 0x4b, 0xb9, 0x4f, 0x1e, 0x32, 0x22, 0x95, 0x65, 0x1b, 0x27,
	0x38, 0x8a, 0x44, 0xc6, 0x95, 0x0d, 0x06, 0x60, 0xd8, 0xf6, 0x77, 0xa9, 0x75, 0x69, 0xb4, 0x19,
	0xce, 0x03, 0x25, 0xe6, 0x84, 0xdb, 0xcd, 0x01, 0x18, 0x9a, 0xe3, 0x1e, 0xaa, 0x26, 0xd4, 0xf6,
	0xdd, 0x1d, 0xd0, 0x95, 0xa0, 0xdc, 0x6f, 0x31, 0x9c, 0xdf, 0x6a, 0x74, 0xd2, 0x7a, 0x5a, 0x39,
	0xe0, 0x65, 0xe5, 0x00, 0xad, 0xba, 0xa1, 0x5c, 0xfd, 0x87, 0xea, 0x13, 0x18, 0x66, 0xe5, 0xb9,
	0xa6, 0x52, 0x59, 0xf7, 0x46, 0x97, 0x51, 0xae, 0x82, 0xb4, 0xac, 0x05, 0x0b, 0x2a, 0xb5, 0xf5,
	0x68, 0x68, 0x8e, 0x21, 0xaa, 0xad, 0x01, 0x1d, 0x8c, 0x39, 0x3d, 0xfb, 0x7a, 0x77, 0xec, 0x25,
	0x66, 0x8b, 0x89, 0x5b, 0x6b, 0xe1, 0xfa, 0x1d, 0xb6, 0x47, 0x77, 0xa6, 0x30, 0x4b, 0xf9, 0x6f,
	0x53, 0xf3, 0x4f, 0xd3, 0xc1, 0xdb, 0x1f, 0x9a, 0x6a, 0x2d, 0x5c, 0xbf, 0x13, 0xee, 0x51, 0x6d,
	0x9a, 0x9e, 0xbf, 0x6e, 0x20, 0x58, 0x6f, 0x20, 0xf8, 0xd8, 0x40, 0xf0, 0xbc, 0x85, 0x8d, 0xf5,
	0x16, 0x36, 0xde, 0xb6, 0xb0, 0x71, 0x67, 0xe6, 0xc5, 0xb7, 0x53, 0xcb, 0x84, 0xc8, 0xf0, 0xb8,
	0xd8, 0xf3, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x51, 0x3d, 0xf9, 0x90, 0x02, 0x00,
	0x00,
}

func (m *BurnRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BurnRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BurnRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxToken != nil {
		{
			size, err := m.MaxToken.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintExpstack(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintExpstack(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MintRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxToken != nil {
		{
			size, err := m.MaxToken.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintExpstack(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintExpstack(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RequestList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BurnRequestList) > 0 {
		for iNdEx := len(m.BurnRequestList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BurnRequestList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintExpstack(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.MintRequestList) > 0 {
		for iNdEx := len(m.MintRequestList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MintRequestList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintExpstack(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintExpstack(dAtA []byte, offset int, v uint64) int {
	offset -= sovExpstack(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BurnRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovExpstack(uint64(l))
	}
	if m.MaxToken != nil {
		l = m.MaxToken.Size()
		n += 1 + l + sovExpstack(uint64(l))
	}
	return n
}

func (m *MintRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovExpstack(uint64(l))
	}
	if m.MaxToken != nil {
		l = m.MaxToken.Size()
		n += 1 + l + sovExpstack(uint64(l))
	}
	return n
}

func (m *RequestList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MintRequestList) > 0 {
		for _, e := range m.MintRequestList {
			l = e.Size()
			n += 1 + l + sovExpstack(uint64(l))
		}
	}
	if len(m.BurnRequestList) > 0 {
		for _, e := range m.BurnRequestList {
			l = e.Size()
			n += 1 + l + sovExpstack(uint64(l))
		}
	}
	return n
}

func sovExpstack(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozExpstack(x uint64) (n int) {
	return sovExpstack(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BurnRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExpstack
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BurnRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BurnRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpstack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpstack
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpstack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpstack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExpstack
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExpstack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MaxToken == nil {
				m.MaxToken = &types.Coin{}
			}
			if err := m.MaxToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExpstack(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExpstack
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MintRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExpstack
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpstack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExpstack
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExpstack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpstack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExpstack
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExpstack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MaxToken == nil {
				m.MaxToken = &types.Coin{}
			}
			if err := m.MaxToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExpstack(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExpstack
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExpstack
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRequestList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpstack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExpstack
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExpstack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintRequestList = append(m.MintRequestList, &MintRequest{})
			if err := m.MintRequestList[len(m.MintRequestList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnRequestList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExpstack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExpstack
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExpstack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BurnRequestList = append(m.BurnRequestList, &BurnRequest{})
			if err := m.BurnRequestList[len(m.BurnRequestList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExpstack(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExpstack
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExpstack(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExpstack
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExpstack
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExpstack
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExpstack
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupExpstack
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthExpstack
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthExpstack        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExpstack          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupExpstack = fmt.Errorf("proto: unexpected end of group")
)
