// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: craft/exp/v1beta1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/x/auth/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params holds parameters for the exp module
type Params struct {
	MaxCoinMint      uint64        `protobuf:"varint,1,opt,name=max_coin_mint,json=maxCoinMint,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"max_coin_mint,omitempty" yaml:"max_coin_mint"`
	DaoAccount       string        `protobuf:"bytes,2,opt,name=daoAccount,proto3" json:"daoAccount,omitempty"`
	Denom            string        `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	IbcAssetDenom    string        `protobuf:"bytes,4,opt,name=ibc_asset_denom,json=ibcAssetDenom,proto3" json:"ibc_asset_denom,omitempty"`
	ClosePoolPeriod  time.Duration `protobuf:"bytes,5,opt,name=close_pool_period,json=closePoolPeriod,proto3,stdduration" json:"close_pool_period"`
	VestingPeriodEnd time.Duration `protobuf:"bytes,6,opt,name=vesting_period_end,json=vestingPeriodEnd,proto3,stdduration" json:"vesting_period_end"`
	BurnExpPeriod    time.Duration `protobuf:"bytes,7,opt,name=burn_exp_period,json=burnExpPeriod,proto3,stdduration" json:"burn_exp_period"`
	ScriptId         uint64        `protobuf:"varint,8,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	AskCount         uint64        `protobuf:"varint,9,opt,name=ask_count,json=askCount,proto3" json:"ask_count,omitempty"`
	MinCount         uint64        `protobuf:"varint,10,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	FeeAmount        types1.Coin   `protobuf:"bytes,11,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount" yaml:"fee_amount"`
	PrepareGas       uint64        `protobuf:"varint,12,opt,name=prepare_gas,json=prepareGas,proto3" json:"prepare_gas,omitempty"`
	ExecuteGas       uint64        `protobuf:"varint,13,opt,name=execute_gas,json=executeGas,proto3" json:"execute_gas,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_5733908f4a86ced5, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxCoinMint() uint64 {
	if m != nil {
		return m.MaxCoinMint
	}
	return 0
}

func (m *Params) GetDaoAccount() string {
	if m != nil {
		return m.DaoAccount
	}
	return ""
}

func (m *Params) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Params) GetIbcAssetDenom() string {
	if m != nil {
		return m.IbcAssetDenom
	}
	return ""
}

func (m *Params) GetClosePoolPeriod() time.Duration {
	if m != nil {
		return m.ClosePoolPeriod
	}
	return 0
}

func (m *Params) GetVestingPeriodEnd() time.Duration {
	if m != nil {
		return m.VestingPeriodEnd
	}
	return 0
}

func (m *Params) GetBurnExpPeriod() time.Duration {
	if m != nil {
		return m.BurnExpPeriod
	}
	return 0
}

func (m *Params) GetScriptId() uint64 {
	if m != nil {
		return m.ScriptId
	}
	return 0
}

func (m *Params) GetAskCount() uint64 {
	if m != nil {
		return m.AskCount
	}
	return 0
}

func (m *Params) GetMinCount() uint64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *Params) GetFeeAmount() types1.Coin {
	if m != nil {
		return m.FeeAmount
	}
	return types1.Coin{}
}

func (m *Params) GetPrepareGas() uint64 {
	if m != nil {
		return m.PrepareGas
	}
	return 0
}

func (m *Params) GetExecuteGas() uint64 {
	if m != nil {
		return m.ExecuteGas
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "craft.exp.v1beta1.Params")
}

func init() { proto.RegisterFile("craft/exp/v1beta1/params.proto", fileDescriptor_5733908f4a86ced5) }

var fileDescriptor_5733908f4a86ced5 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x63, 0x68, 0x43, 0xb2, 0x21, 0x0a, 0xb1, 0x72, 0x70, 0x5a, 0xc9, 0x8e, 0x22, 0x81,
	0x72, 0xc1, 0x56, 0xe1, 0xc6, 0x2d, 0x69, 0xab, 0x82, 0x10, 0x22, 0x84, 0x1b, 0x97, 0xd5, 0xda,
	0xde, 0xb8, 0xab, 0x78, 0x3f, 0xe4, 0x5d, 0x57, 0xee, 0x5b, 0x70, 0xe4, 0x19, 0xb8, 0xf2, 0x12,
	0x39, 0xf6, 0xc8, 0x29, 0x45, 0xc9, 0x1b, 0xf4, 0x09, 0x90, 0x77, 0x37, 0xe5, 0xe3, 0xd4, 0x93,
	0x77, 0xe6, 0x37, 0x33, 0xfb, 0xd7, 0x7f, 0xc7, 0xc0, 0x4f, 0x0a, 0xb4, 0x54, 0x11, 0xae, 0x44,
	0x74, 0x75, 0x12, 0x63, 0x85, 0x4e, 0x22, 0x81, 0x0a, 0x44, 0x65, 0x28, 0x0a, 0xae, 0xb8, 0xdb,
	0xd7, 0x3c, 0xc4, 0x95, 0x08, 0x2d, 0x3f, 0x1a, 0x64, 0x3c, 0xe3, 0x9a, 0x46, 0xf5, 0xc9, 0x14,
	0x1e, 0x0d, 0x13, 0x2e, 0x29, 0x97, 0xd0, 0x00, 0x13, 0x58, 0xe4, 0x9b, 0x28, 0x8a, 0x91, 0xc4,
	0xf7, 0xb7, 0x24, 0x9c, 0xb0, 0xff, 0x38, 0x2a, 0xd5, 0xe5, 0x3d, 0xaf, 0x83, 0x3d, 0xcf, 0x38,
	0xcf, 0x72, 0x1c, 0xe9, 0x28, 0x2e, 0x97, 0x51, 0x5a, 0x16, 0x48, 0x11, 0x6e, 0xfb, 0xc7, 0x3f,
	0x0e, 0x41, 0x73, 0xae, 0x45, 0xbb, 0x39, 0xe8, 0x52, 0x54, 0xc1, 0x7a, 0x38, 0xa4, 0x84, 0x29,
	0xcf, 0x19, 0x39, 0x93, 0x83, 0xd9, 0xdb, 0xf5, 0x26, 0x70, 0xee, 0x36, 0xc1, 0xe0, 0x1a, 0xd1,
	0xfc, 0xcd, 0xf8, 0x9f, 0x92, 0xf1, 0xf7, 0xdb, 0x60, 0x92, 0x11, 0x75, 0x59, 0xc6, 0x61, 0xc2,
	0xa9, 0x95, 0x6e, 0x3f, 0x2f, 0x65, 0xba, 0x8a, 0xd4, 0xb5, 0xc0, 0x32, 0x3c, 0xe5, 0x84, 0xc9,
	0x45, 0x87, 0xa2, 0xaa, 0x3e, 0x7d, 0x20, 0x4c, 0xb9, 0x3e, 0x00, 0x29, 0xe2, 0xd3, 0x24, 0xe1,
	0x25, 0x53, 0xde, 0xa3, 0x91, 0x33, 0x69, 0x2f, 0xfe, 0xca, 0xb8, 0x03, 0x70, 0x98, 0x62, 0xc6,
	0xa9, 0xf7, 0x58, 0x23, 0x13, 0xb8, 0x2f, 0x40, 0x8f, 0xc4, 0x09, 0x44, 0x52, 0x62, 0x05, 0x0d,
	0x3f, 0xd0, 0xbc, 0x4b, 0xe2, 0x64, 0x5a, 0x67, 0xcf, 0x74, 0xdd, 0x47, 0xd0, 0x4f, 0x72, 0x2e,
	0x31, 0x14, 0x9c, 0xe7, 0x50, 0xe0, 0x82, 0xf0, 0xd4, 0x3b, 0x1c, 0x39, 0x93, 0xce, 0xab, 0x61,
	0x68, 0x2c, 0x09, 0xf7, 0x96, 0x84, 0x67, 0xd6, 0x92, 0x59, 0x6b, 0xbd, 0x09, 0x1a, 0xdf, 0x6e,
	0x03, 0x67, 0xd1, 0xd3, 0xdd, 0x73, 0xce, 0xf3, 0xb9, 0xee, 0x75, 0x3f, 0x01, 0xf7, 0x0a, 0x4b,
	0x45, 0x58, 0x66, 0xa7, 0x41, 0xcc, 0x52, 0xaf, 0xf9, 0xf0, 0x89, 0xcf, 0x6c, 0xbb, 0x99, 0x77,
	0xce, 0x52, 0xf7, 0x3d, 0xe8, 0xc5, 0x65, 0xc1, 0x20, 0xae, 0xc4, 0x5e, 0xe1, 0x93, 0x87, 0xcf,
	0xeb, 0xd6, 0xbd, 0xe7, 0x95, 0xb0, 0xfa, 0x8e, 0x41, 0x5b, 0x26, 0x05, 0x11, 0x0a, 0x92, 0xd4,
	0x6b, 0xd5, 0x0f, 0xb7, 0x68, 0x99, 0xc4, 0x3b, 0x0d, 0x91, 0x5c, 0x41, 0x63, 0x75, 0xdb, 0x40,
	0x24, 0x57, 0xa7, 0xda, 0xe8, 0x63, 0xd0, 0xa6, 0x84, 0x59, 0x08, 0x0c, 0xa4, 0x84, 0x19, 0xf8,
	0x19, 0x80, 0x25, 0xc6, 0x10, 0x51, 0x4d, 0x3b, 0x56, 0x9e, 0xdd, 0xd0, 0x7a, 0x27, 0xf7, 0x9b,
	0xad, 0x9f, 0x78, 0x36, 0xac, 0xe5, 0xdd, 0x6d, 0x82, 0xbe, 0xd9, 0x95, 0x3f, 0xad, 0xe3, 0x45,
	0x7b, 0x89, 0xf1, 0x54, 0x9f, 0xdd, 0x00, 0x74, 0x44, 0x81, 0x05, 0x2a, 0x30, 0xcc, 0x90, 0xf4,
	0x9e, 0xea, 0x3b, 0x81, 0x4d, 0x5d, 0x20, 0x59, 0x17, 0xe0, 0x0a, 0x27, 0xa5, 0x32, 0x05, 0x5d,
	0x53, 0x60, 0x53, 0x17, 0x48, 0xce, 0x9e, 0xaf, 0xb7, 0xbe, 0x73, 0xb3, 0xf5, 0x9d, 0x5f, 0x5b,
	0xdf, 0xf9, 0xba, 0xf3, 0x1b, 0x37, 0x3b, 0xbf, 0xf1, 0x73, 0xe7, 0x37, 0xbe, 0x74, 0x2a, 0xfd,
	0x3f, 0xea, 0xb5, 0x8b, 0x9b, 0xda, 0xc0, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x42, 0xa7,
	0xb9, 0xb1, 0xa9, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExecuteGas != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ExecuteGas))
		i--
		dAtA[i] = 0x68
	}
	if m.PrepareGas != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PrepareGas))
		i--
		dAtA[i] = 0x60
	}
	{
		size, err := m.FeeAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if m.MinCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinCount))
		i--
		dAtA[i] = 0x50
	}
	if m.AskCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AskCount))
		i--
		dAtA[i] = 0x48
	}
	if m.ScriptId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ScriptId))
		i--
		dAtA[i] = 0x40
	}
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.BurnExpPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.BurnExpPeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x3a
	n3, err3 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.VestingPeriodEnd, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.VestingPeriodEnd):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x32
	n4, err4 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.ClosePoolPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.ClosePoolPeriod):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintParams(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x2a
	if len(m.IbcAssetDenom) > 0 {
		i -= len(m.IbcAssetDenom)
		copy(dAtA[i:], m.IbcAssetDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IbcAssetDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DaoAccount) > 0 {
		i -= len(m.DaoAccount)
		copy(dAtA[i:], m.DaoAccount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DaoAccount)))
		i--
		dAtA[i] = 0x12
	}
	if m.MaxCoinMint != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxCoinMint))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxCoinMint != 0 {
		n += 1 + sovParams(uint64(m.MaxCoinMint))
	}
	l = len(m.DaoAccount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.IbcAssetDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.ClosePoolPeriod)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.VestingPeriodEnd)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.BurnExpPeriod)
	n += 1 + l + sovParams(uint64(l))
	if m.ScriptId != 0 {
		n += 1 + sovParams(uint64(m.ScriptId))
	}
	if m.AskCount != 0 {
		n += 1 + sovParams(uint64(m.AskCount))
	}
	if m.MinCount != 0 {
		n += 1 + sovParams(uint64(m.MinCount))
	}
	l = m.FeeAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.PrepareGas != 0 {
		n += 1 + sovParams(uint64(m.PrepareGas))
	}
	if m.ExecuteGas != 0 {
		n += 1 + sovParams(uint64(m.ExecuteGas))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCoinMint", wireType)
			}
			m.MaxCoinMint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCoinMint |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DaoAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcAssetDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcAssetDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClosePoolPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.ClosePoolPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingPeriodEnd", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.VestingPeriodEnd, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnExpPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.BurnExpPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptId", wireType)
			}
			m.ScriptId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScriptId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskCount", wireType)
			}
			m.AskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCount", wireType)
			}
			m.MinCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareGas", wireType)
			}
			m.PrepareGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteGas", wireType)
			}
			m.ExecuteGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecuteGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
