// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: craft/exp/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryWhiteListRequest struct {
}

func (m *QueryWhiteListRequest) Reset()         { *m = QueryWhiteListRequest{} }
func (m *QueryWhiteListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWhiteListRequest) ProtoMessage()    {}
func (*QueryWhiteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b68876adaf3112f, []int{0}
}
func (m *QueryWhiteListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWhiteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWhiteListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWhiteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWhiteListRequest.Merge(m, src)
}
func (m *QueryWhiteListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWhiteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWhiteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWhiteListRequest proto.InternalMessageInfo

type QueryWhiteListResponse struct {
	AccountRecord []*AccountRecord `protobuf:"bytes,1,rep,name=accountRecord,proto3" json:"accountRecord,omitempty"`
}

func (m *QueryWhiteListResponse) Reset()         { *m = QueryWhiteListResponse{} }
func (m *QueryWhiteListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWhiteListResponse) ProtoMessage()    {}
func (*QueryWhiteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b68876adaf3112f, []int{1}
}
func (m *QueryWhiteListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWhiteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWhiteListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWhiteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWhiteListResponse.Merge(m, src)
}
func (m *QueryWhiteListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWhiteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWhiteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWhiteListResponse proto.InternalMessageInfo

func (m *QueryWhiteListResponse) GetAccountRecord() []*AccountRecord {
	if m != nil {
		return m.AccountRecord
	}
	return nil
}

type QueryDaoTokenPriceRequest struct {
}

func (m *QueryDaoTokenPriceRequest) Reset()         { *m = QueryDaoTokenPriceRequest{} }
func (m *QueryDaoTokenPriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDaoTokenPriceRequest) ProtoMessage()    {}
func (*QueryDaoTokenPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b68876adaf3112f, []int{2}
}
func (m *QueryDaoTokenPriceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDaoTokenPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDaoTokenPriceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDaoTokenPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDaoTokenPriceRequest.Merge(m, src)
}
func (m *QueryDaoTokenPriceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDaoTokenPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDaoTokenPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDaoTokenPriceRequest proto.InternalMessageInfo

type QueryDaoTokenPriceResponse struct {
	DaoTokenPrice string `protobuf:"bytes,1,opt,name=dao_token_price,json=daoTokenPrice,proto3" json:"dao_token_price,omitempty"`
}

func (m *QueryDaoTokenPriceResponse) Reset()         { *m = QueryDaoTokenPriceResponse{} }
func (m *QueryDaoTokenPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDaoTokenPriceResponse) ProtoMessage()    {}
func (*QueryDaoTokenPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b68876adaf3112f, []int{3}
}
func (m *QueryDaoTokenPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDaoTokenPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDaoTokenPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDaoTokenPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDaoTokenPriceResponse.Merge(m, src)
}
func (m *QueryDaoTokenPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDaoTokenPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDaoTokenPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDaoTokenPriceResponse proto.InternalMessageInfo

func (m *QueryDaoTokenPriceResponse) GetDaoTokenPrice() string {
	if m != nil {
		return m.DaoTokenPrice
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryWhiteListRequest)(nil), "craft.exp.v1beta1.QueryWhiteListRequest")
	proto.RegisterType((*QueryWhiteListResponse)(nil), "craft.exp.v1beta1.QueryWhiteListResponse")
	proto.RegisterType((*QueryDaoTokenPriceRequest)(nil), "craft.exp.v1beta1.QueryDaoTokenPriceRequest")
	proto.RegisterType((*QueryDaoTokenPriceResponse)(nil), "craft.exp.v1beta1.QueryDaoTokenPriceResponse")
}

func init() { proto.RegisterFile("craft/exp/v1beta1/query.proto", fileDescriptor_6b68876adaf3112f) }

var fileDescriptor_6b68876adaf3112f = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x8a, 0x13, 0x41,
	0x10, 0xc6, 0xd3, 0x11, 0x85, 0x74, 0x08, 0x62, 0xe3, 0x9f, 0x38, 0xea, 0x64, 0x1c, 0x50, 0x47,
	0xd1, 0x69, 0x12, 0x9f, 0x40, 0x09, 0x9e, 0x3c, 0xe8, 0x20, 0x08, 0x5e, 0x62, 0x67, 0xa6, 0x33,
	0x36, 0xc6, 0xae, 0xce, 0x74, 0x47, 0x93, 0xab, 0x37, 0x6f, 0xc2, 0xc2, 0x3e, 0xc5, 0x3e, 0xc8,
	0x1e, 0x03, 0x7b, 0xd9, 0xe3, 0x92, 0xec, 0x83, 0x2c, 0xd3, 0x33, 0x1b, 0x92, 0xcd, 0x2c, 0xe4,
	0xd6, 0xf4, 0xf7, 0x55, 0xd5, 0xaf, 0x3e, 0x0a, 0x3f, 0x89, 0x33, 0x36, 0x32, 0x94, 0xcf, 0x14,
	0xfd, 0xdd, 0x1d, 0x72, 0xc3, 0xba, 0x74, 0x32, 0xe5, 0xd9, 0x3c, 0x54, 0x19, 0x18, 0x20, 0x77,
	0xac, 0x1c, 0xf2, 0x99, 0x0a, 0x4b, 0xd9, 0xe9, 0xec, 0x56, 0x24, 0x0c, 0x84, 0x1c, 0x41, 0x51,
	0xe3, 0x3c, 0x4e, 0x01, 0xd2, 0x31, 0xa7, 0x4c, 0x09, 0xca, 0xa4, 0x04, 0xc3, 0x8c, 0x00, 0xa9,
	0x4b, 0xf5, 0x6e, 0x0a, 0x29, 0xd8, 0x27, 0xcd, 0x5f, 0xe5, 0xef, 0xab, 0x18, 0xf4, 0x2f, 0xd0,
	0x74, 0xc8, 0x34, 0x2f, 0x00, 0xd6, 0xcd, 0x15, 0x4b, 0x85, 0xb4, 0x2d, 0x0a, 0xaf, 0xff, 0x00,
	0xdf, 0xfb, 0x9c, 0x3b, 0xbe, 0xfe, 0x10, 0x86, 0x7f, 0x14, 0xda, 0x44, 0x7c, 0x32, 0xe5, 0xda,
	0xf8, 0xdf, 0xf1, 0xfd, 0xab, 0x82, 0x56, 0x20, 0x35, 0x27, 0x1f, 0x70, 0x8b, 0xc5, 0x31, 0x4c,
	0xa5, 0x89, 0x78, 0x0c, 0x59, 0xd2, 0x46, 0xde, 0x8d, 0xa0, 0xd9, 0xf3, 0xc2, 0x9d, 0xf5, 0xc2,
	0x77, 0x9b, 0xbe, 0x68, 0xbb, 0xcc, 0x7f, 0x84, 0x1f, 0xda, 0x09, 0x7d, 0x06, 0x5f, 0xe0, 0x27,
	0x97, 0x9f, 0x32, 0x11, 0xf3, 0xcb, 0xf1, 0x7d, 0xec, 0x54, 0x89, 0x25, 0xc2, 0x73, 0x7c, 0x3b,
	0x61, 0x30, 0x30, 0xb9, 0x32, 0x50, 0xb9, 0xd4, 0x46, 0x1e, 0x0a, 0x1a, 0x51, 0x2b, 0xd9, 0xf4,
	0xf7, 0x8e, 0xea, 0xf8, 0xa6, 0x6d, 0x43, 0xfe, 0x21, 0xdc, 0x58, 0xaf, 0x42, 0x82, 0x0a, 0xd6,
	0xca, 0x18, 0x9c, 0x97, 0x7b, 0x38, 0x0b, 0x28, 0xff, 0xc5, 0xdf, 0x93, 0xf3, 0x83, 0xfa, 0x53,
	0xd2, 0xa1, 0x3b, 0x25, 0xf4, 0x4f, 0xee, 0x1e, 0x0b, 0x6d, 0x12, 0x06, 0xe4, 0x10, 0xe1, 0xd6,
	0xd6, 0x5e, 0xe4, 0xf5, 0x75, 0x53, 0xaa, 0xb2, 0x71, 0xde, 0xec, 0xe9, 0x2e, 0xb9, 0x02, 0xcb,
	0xe5, 0x13, 0xaf, 0x82, 0x2b, 0x61, 0x60, 0x43, 0xb4, 0x19, 0xbe, 0x7f, 0x76, 0xbc, 0x74, 0xd1,
	0x62, 0xe9, 0xa2, 0xb3, 0xa5, 0x8b, 0xfe, 0xaf, 0xdc, 0xda, 0x62, 0xe5, 0xd6, 0x4e, 0x57, 0x6e,
	0xed, 0x5b, 0x73, 0x66, 0x6f, 0xd4, 0xcc, 0x15, 0xd7, 0xc3, 0x5b, 0xf6, 0x74, 0xde, 0x5e, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x78, 0x2d, 0x7b, 0xf2, 0xef, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// returns coins that is going to be distributed
	WhiteList(ctx context.Context, in *QueryWhiteListRequest, opts ...grpc.CallOption) (*QueryWhiteListResponse, error)
	DaoTokenPrice(ctx context.Context, in *QueryDaoTokenPriceRequest, opts ...grpc.CallOption) (*QueryDaoTokenPriceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) WhiteList(ctx context.Context, in *QueryWhiteListRequest, opts ...grpc.CallOption) (*QueryWhiteListResponse, error) {
	out := new(QueryWhiteListResponse)
	err := c.cc.Invoke(ctx, "/craft.exp.v1beta1.Query/WhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DaoTokenPrice(ctx context.Context, in *QueryDaoTokenPriceRequest, opts ...grpc.CallOption) (*QueryDaoTokenPriceResponse, error) {
	out := new(QueryDaoTokenPriceResponse)
	err := c.cc.Invoke(ctx, "/craft.exp.v1beta1.Query/DaoTokenPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// returns coins that is going to be distributed
	WhiteList(context.Context, *QueryWhiteListRequest) (*QueryWhiteListResponse, error)
	DaoTokenPrice(context.Context, *QueryDaoTokenPriceRequest) (*QueryDaoTokenPriceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) WhiteList(ctx context.Context, req *QueryWhiteListRequest) (*QueryWhiteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhiteList not implemented")
}
func (*UnimplementedQueryServer) DaoTokenPrice(ctx context.Context, req *QueryDaoTokenPriceRequest) (*QueryDaoTokenPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DaoTokenPrice not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_WhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWhiteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/craft.exp.v1beta1.Query/WhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WhiteList(ctx, req.(*QueryWhiteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DaoTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDaoTokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DaoTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/craft.exp.v1beta1.Query/DaoTokenPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DaoTokenPrice(ctx, req.(*QueryDaoTokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "craft.exp.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhiteList",
			Handler:    _Query_WhiteList_Handler,
		},
		{
			MethodName: "DaoTokenPrice",
			Handler:    _Query_DaoTokenPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "craft/exp/v1beta1/query.proto",
}

func (m *QueryWhiteListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWhiteListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWhiteListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryWhiteListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWhiteListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWhiteListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccountRecord) > 0 {
		for iNdEx := len(m.AccountRecord) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountRecord[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDaoTokenPriceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDaoTokenPriceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDaoTokenPriceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDaoTokenPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDaoTokenPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDaoTokenPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DaoTokenPrice) > 0 {
		i -= len(m.DaoTokenPrice)
		copy(dAtA[i:], m.DaoTokenPrice)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DaoTokenPrice)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryWhiteListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryWhiteListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AccountRecord) > 0 {
		for _, e := range m.AccountRecord {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryDaoTokenPriceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDaoTokenPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DaoTokenPrice)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryWhiteListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWhiteListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWhiteListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWhiteListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWhiteListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWhiteListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountRecord", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountRecord = append(m.AccountRecord, &AccountRecord{})
			if err := m.AccountRecord[len(m.AccountRecord)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDaoTokenPriceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDaoTokenPriceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDaoTokenPriceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDaoTokenPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDaoTokenPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDaoTokenPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoTokenPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DaoTokenPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
