// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: craft/exp/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgMintAndAllocateExp struct {
	Amount      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
	FromAddress string                                   `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// members defines the Dao members address.
	Member string `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
}

func (m *MsgMintAndAllocateExp) Reset()         { *m = MsgMintAndAllocateExp{} }
func (m *MsgMintAndAllocateExp) String() string { return proto.CompactTextString(m) }
func (*MsgMintAndAllocateExp) ProtoMessage()    {}
func (*MsgMintAndAllocateExp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea0f2c4d268ca6db, []int{0}
}
func (m *MsgMintAndAllocateExp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintAndAllocateExp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintAndAllocateExp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintAndAllocateExp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintAndAllocateExp.Merge(m, src)
}
func (m *MsgMintAndAllocateExp) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintAndAllocateExp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintAndAllocateExp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintAndAllocateExp proto.InternalMessageInfo

func (m *MsgMintAndAllocateExp) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *MsgMintAndAllocateExp) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgMintAndAllocateExp) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

type MsgMintAndAllocateExpResponse struct {
}

func (m *MsgMintAndAllocateExpResponse) Reset()         { *m = MsgMintAndAllocateExpResponse{} }
func (m *MsgMintAndAllocateExpResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMintAndAllocateExpResponse) ProtoMessage()    {}
func (*MsgMintAndAllocateExpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea0f2c4d268ca6db, []int{1}
}
func (m *MsgMintAndAllocateExpResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintAndAllocateExpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintAndAllocateExpResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintAndAllocateExpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintAndAllocateExpResponse.Merge(m, src)
}
func (m *MsgMintAndAllocateExpResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintAndAllocateExpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintAndAllocateExpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintAndAllocateExpResponse proto.InternalMessageInfo

// MsgBurnAndRemoveMember
type MsgBurnAndRemoveMember struct {
	// from_address defines the member who want exit Dao and get their money.
	FromAddress string `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// metadata is any arbitrary metadata to attached.
	Metadata string `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *MsgBurnAndRemoveMember) Reset()         { *m = MsgBurnAndRemoveMember{} }
func (m *MsgBurnAndRemoveMember) String() string { return proto.CompactTextString(m) }
func (*MsgBurnAndRemoveMember) ProtoMessage()    {}
func (*MsgBurnAndRemoveMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea0f2c4d268ca6db, []int{2}
}
func (m *MsgBurnAndRemoveMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBurnAndRemoveMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBurnAndRemoveMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBurnAndRemoveMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnAndRemoveMember.Merge(m, src)
}
func (m *MsgBurnAndRemoveMember) XXX_Size() int {
	return m.Size()
}
func (m *MsgBurnAndRemoveMember) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnAndRemoveMember.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnAndRemoveMember proto.InternalMessageInfo

func (m *MsgBurnAndRemoveMember) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgBurnAndRemoveMember) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type MsgBurnAndRemoveMemberResponse struct {
}

func (m *MsgBurnAndRemoveMemberResponse) Reset()         { *m = MsgBurnAndRemoveMemberResponse{} }
func (m *MsgBurnAndRemoveMemberResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBurnAndRemoveMemberResponse) ProtoMessage()    {}
func (*MsgBurnAndRemoveMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea0f2c4d268ca6db, []int{3}
}
func (m *MsgBurnAndRemoveMemberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBurnAndRemoveMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBurnAndRemoveMemberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBurnAndRemoveMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnAndRemoveMemberResponse.Merge(m, src)
}
func (m *MsgBurnAndRemoveMemberResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBurnAndRemoveMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnAndRemoveMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnAndRemoveMemberResponse proto.InternalMessageInfo

// MsgBurnAndRemoveMember
type MsgJoinDao struct {
	// join_address defines the member who want join Dao.
	JoinAddress string `protobuf:"bytes,1,opt,name=join_address,json=joinAddress,proto3" json:"join_address,omitempty"`
	// gov_address defines the gov chain address.
	GovAddress string `protobuf:"bytes,2,opt,name=gov_address,json=govAddress,proto3" json:"gov_address,omitempty"`
	// max_coin_mint is maximum exp can be mint.
	MaxToken int64 `protobuf:"varint,3,opt,name=max_token,json=maxToken,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Int" json:"max_token,omitempty"`
}

func (m *MsgJoinDao) Reset()         { *m = MsgJoinDao{} }
func (m *MsgJoinDao) String() string { return proto.CompactTextString(m) }
func (*MsgJoinDao) ProtoMessage()    {}
func (*MsgJoinDao) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea0f2c4d268ca6db, []int{4}
}
func (m *MsgJoinDao) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgJoinDao) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgJoinDao.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgJoinDao) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgJoinDao.Merge(m, src)
}
func (m *MsgJoinDao) XXX_Size() int {
	return m.Size()
}
func (m *MsgJoinDao) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgJoinDao.DiscardUnknown(m)
}

var xxx_messageInfo_MsgJoinDao proto.InternalMessageInfo

func (m *MsgJoinDao) GetJoinAddress() string {
	if m != nil {
		return m.JoinAddress
	}
	return ""
}

func (m *MsgJoinDao) GetGovAddress() string {
	if m != nil {
		return m.GovAddress
	}
	return ""
}

func (m *MsgJoinDao) GetMaxToken() int64 {
	if m != nil {
		return m.MaxToken
	}
	return 0
}

type MsgJoinDaoResponse struct {
}

func (m *MsgJoinDaoResponse) Reset()         { *m = MsgJoinDaoResponse{} }
func (m *MsgJoinDaoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgJoinDaoResponse) ProtoMessage()    {}
func (*MsgJoinDaoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea0f2c4d268ca6db, []int{5}
}
func (m *MsgJoinDaoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgJoinDaoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgJoinDaoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgJoinDaoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgJoinDaoResponse.Merge(m, src)
}
func (m *MsgJoinDaoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgJoinDaoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgJoinDaoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgJoinDaoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgMintAndAllocateExp)(nil), "craft.exp.v1beta1.MsgMintAndAllocateExp")
	proto.RegisterType((*MsgMintAndAllocateExpResponse)(nil), "craft.exp.v1beta1.MsgMintAndAllocateExpResponse")
	proto.RegisterType((*MsgBurnAndRemoveMember)(nil), "craft.exp.v1beta1.MsgBurnAndRemoveMember")
	proto.RegisterType((*MsgBurnAndRemoveMemberResponse)(nil), "craft.exp.v1beta1.MsgBurnAndRemoveMemberResponse")
	proto.RegisterType((*MsgJoinDao)(nil), "craft.exp.v1beta1.MsgJoinDao")
	proto.RegisterType((*MsgJoinDaoResponse)(nil), "craft.exp.v1beta1.MsgJoinDaoResponse")
}

func init() { proto.RegisterFile("craft/exp/v1beta1/tx.proto", fileDescriptor_ea0f2c4d268ca6db) }

var fileDescriptor_ea0f2c4d268ca6db = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe3, 0x46, 0x0a, 0xed, 0x84, 0x0b, 0xa6, 0x54, 0xc1, 0x52, 0x9d, 0x60, 0xa9, 0x28,
	0x20, 0xb1, 0x6e, 0xca, 0x13, 0x24, 0x80, 0x10, 0x48, 0x16, 0x92, 0x85, 0x84, 0xc4, 0xa5, 0x5a,
	0xdb, 0xdb, 0xc5, 0xb4, 0xbb, 0x63, 0x79, 0x37, 0x91, 0x79, 0x0b, 0xae, 0xbc, 0x42, 0x5f, 0x80,
	0x13, 0xf7, 0x1e, 0x7b, 0xe4, 0x44, 0x51, 0xf2, 0x22, 0xc8, 0x6b, 0x3b, 0x48, 0x8d, 0x55, 0xe5,
	0x64, 0xef, 0xfc, 0x33, 0xff, 0x37, 0x9a, 0xd9, 0x05, 0x27, 0xce, 0xe9, 0x99, 0xf6, 0x59, 0x91,
	0xf9, 0x8b, 0x49, 0xc4, 0x34, 0x9d, 0xf8, 0xba, 0x20, 0x59, 0x8e, 0x1a, 0xed, 0x07, 0x46, 0x23,
	0xac, 0xc8, 0x48, 0xad, 0x39, 0xfb, 0x1c, 0x39, 0x1a, 0xd5, 0x2f, 0xff, 0xaa, 0x44, 0xc7, 0x8d,
	0x51, 0x09, 0x54, 0x7e, 0x44, 0x15, 0x5b, 0xdb, 0xc4, 0x98, 0xca, 0x4a, 0xf7, 0x7e, 0x5a, 0xf0,
	0x28, 0x50, 0x3c, 0x48, 0xa5, 0x9e, 0xca, 0x64, 0x7a, 0x71, 0x81, 0x31, 0xd5, 0xec, 0x4d, 0x91,
	0xd9, 0x31, 0xf4, 0xa8, 0xc0, 0xb9, 0xd4, 0x03, 0x6b, 0xd4, 0x1d, 0xf7, 0x4f, 0x1e, 0x93, 0xca,
	0x8a, 0x94, 0x56, 0x0d, 0x95, 0xbc, 0xc2, 0x54, 0xce, 0x8e, 0xaf, 0xfe, 0x0c, 0x3b, 0x97, 0x37,
	0xc3, 0x31, 0x4f, 0xf5, 0x97, 0x79, 0x44, 0x62, 0x14, 0x7e, 0xcd, 0xad, 0x3e, 0x2f, 0x54, 0x72,
	0xee, 0xeb, 0x6f, 0x19, 0x53, 0xa6, 0x40, 0x85, 0xb5, 0xb5, 0xfd, 0x04, 0xee, 0x9f, 0xe5, 0x28,
	0x4e, 0x69, 0x92, 0xe4, 0x4c, 0xa9, 0xc1, 0xce, 0xc8, 0x1a, 0xef, 0x85, 0xfd, 0x32, 0x36, 0xad,
	0x42, 0xf6, 0x01, 0xf4, 0x04, 0x13, 0x11, 0xcb, 0x07, 0x5d, 0x23, 0xd6, 0x27, 0x6f, 0x08, 0x87,
	0xad, 0x8d, 0x87, 0x4c, 0x65, 0x28, 0x15, 0xf3, 0x3e, 0xc1, 0x41, 0xa0, 0xf8, 0x6c, 0x9e, 0xcb,
	0xa9, 0x4c, 0x42, 0x26, 0x70, 0xc1, 0x02, 0x53, 0xba, 0x41, 0xb5, 0x36, 0xa9, 0x0e, 0xec, 0x0a,
	0xa6, 0x69, 0x42, 0x35, 0xad, 0x9b, 0x5a, 0x9f, 0xbd, 0x11, 0xb8, 0xed, 0xc6, 0x6b, 0xf4, 0x0f,
	0x0b, 0x20, 0x50, 0xfc, 0x3d, 0xa6, 0xf2, 0x35, 0xc5, 0x92, 0xf7, 0x15, 0x53, 0x79, 0x9b, 0x57,
	0xc6, 0x1a, 0xde, 0x10, 0xfa, 0x1c, 0x17, 0xb7, 0xe6, 0x00, 0x1c, 0x17, 0x4d, 0xc2, 0x5b, 0xd8,
	0x13, 0xb4, 0x38, 0xd5, 0x78, 0xce, 0xa4, 0x99, 0x44, 0x77, 0xf6, 0xfc, 0xf2, 0x66, 0xf8, 0x74,
	0x8b, 0x91, 0xbf, 0x93, 0x3a, 0xdc, 0x15, 0xb4, 0xf8, 0x58, 0xd6, 0x7a, 0xfb, 0x60, 0xff, 0x6f,
	0xad, 0xe9, 0xf8, 0xe4, 0xd7, 0x0e, 0x74, 0x03, 0xc5, 0xed, 0x0c, 0xec, 0x96, 0xbb, 0x30, 0x26,
	0x1b, 0xf7, 0x8d, 0xb4, 0x0e, 0xdf, 0x39, 0xde, 0x36, 0xb3, 0x21, 0xdb, 0x0a, 0x1e, 0xb6, 0xed,
	0xe8, 0x59, 0xbb, 0x51, 0x4b, 0xaa, 0x33, 0xd9, 0x3a, 0x75, 0x0d, 0xfd, 0x00, 0xf7, 0x9a, 0xe5,
	0x1c, 0xb6, 0x57, 0xd7, 0xb2, 0x73, 0x74, 0xa7, 0xdc, 0x18, 0xce, 0x8e, 0xae, 0x96, 0xae, 0x75,
	0xbd, 0x74, 0xad, 0xbf, 0x4b, 0xd7, 0xfa, 0xbe, 0x72, 0x3b, 0xd7, 0x2b, 0xb7, 0xf3, 0x7b, 0xe5,
	0x76, 0x3e, 0xf7, 0x0b, 0xf3, 0x84, 0xcd, 0x2a, 0xa2, 0x9e, 0x79, 0x75, 0x2f, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0x97, 0x73, 0x18, 0xdc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	MintAndAllocateExp(ctx context.Context, in *MsgMintAndAllocateExp, opts ...grpc.CallOption) (*MsgMintAndAllocateExpResponse, error)
	BurnAndRemoveMember(ctx context.Context, in *MsgBurnAndRemoveMember, opts ...grpc.CallOption) (*MsgBurnAndRemoveMemberResponse, error)
	JoinDao(ctx context.Context, in *MsgJoinDao, opts ...grpc.CallOption) (*MsgJoinDaoResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) MintAndAllocateExp(ctx context.Context, in *MsgMintAndAllocateExp, opts ...grpc.CallOption) (*MsgMintAndAllocateExpResponse, error) {
	out := new(MsgMintAndAllocateExpResponse)
	err := c.cc.Invoke(ctx, "/craft.exp.v1beta1.Msg/MintAndAllocateExp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BurnAndRemoveMember(ctx context.Context, in *MsgBurnAndRemoveMember, opts ...grpc.CallOption) (*MsgBurnAndRemoveMemberResponse, error) {
	out := new(MsgBurnAndRemoveMemberResponse)
	err := c.cc.Invoke(ctx, "/craft.exp.v1beta1.Msg/BurnAndRemoveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) JoinDao(ctx context.Context, in *MsgJoinDao, opts ...grpc.CallOption) (*MsgJoinDaoResponse, error) {
	out := new(MsgJoinDaoResponse)
	err := c.cc.Invoke(ctx, "/craft.exp.v1beta1.Msg/JoinDao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	MintAndAllocateExp(context.Context, *MsgMintAndAllocateExp) (*MsgMintAndAllocateExpResponse, error)
	BurnAndRemoveMember(context.Context, *MsgBurnAndRemoveMember) (*MsgBurnAndRemoveMemberResponse, error)
	JoinDao(context.Context, *MsgJoinDao) (*MsgJoinDaoResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) MintAndAllocateExp(ctx context.Context, req *MsgMintAndAllocateExp) (*MsgMintAndAllocateExpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintAndAllocateExp not implemented")
}
func (*UnimplementedMsgServer) BurnAndRemoveMember(ctx context.Context, req *MsgBurnAndRemoveMember) (*MsgBurnAndRemoveMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnAndRemoveMember not implemented")
}
func (*UnimplementedMsgServer) JoinDao(ctx context.Context, req *MsgJoinDao) (*MsgJoinDaoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinDao not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_MintAndAllocateExp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintAndAllocateExp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintAndAllocateExp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/craft.exp.v1beta1.Msg/MintAndAllocateExp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintAndAllocateExp(ctx, req.(*MsgMintAndAllocateExp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BurnAndRemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBurnAndRemoveMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BurnAndRemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/craft.exp.v1beta1.Msg/BurnAndRemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BurnAndRemoveMember(ctx, req.(*MsgBurnAndRemoveMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_JoinDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgJoinDao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).JoinDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/craft.exp.v1beta1.Msg/JoinDao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).JoinDao(ctx, req.(*MsgJoinDao))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "craft.exp.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintAndAllocateExp",
			Handler:    _Msg_MintAndAllocateExp_Handler,
		},
		{
			MethodName: "BurnAndRemoveMember",
			Handler:    _Msg_BurnAndRemoveMember_Handler,
		},
		{
			MethodName: "JoinDao",
			Handler:    _Msg_JoinDao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "craft/exp/v1beta1/tx.proto",
}

func (m *MsgMintAndAllocateExp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintAndAllocateExp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintAndAllocateExp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Member) > 0 {
		i -= len(m.Member)
		copy(dAtA[i:], m.Member)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Member)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MsgMintAndAllocateExpResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintAndAllocateExpResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintAndAllocateExpResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgBurnAndRemoveMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBurnAndRemoveMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBurnAndRemoveMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBurnAndRemoveMemberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBurnAndRemoveMemberResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBurnAndRemoveMemberResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgJoinDao) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgJoinDao) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgJoinDao) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxToken != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MaxToken))
		i--
		dAtA[i] = 0x18
	}
	if len(m.GovAddress) > 0 {
		i -= len(m.GovAddress)
		copy(dAtA[i:], m.GovAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GovAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.JoinAddress) > 0 {
		i -= len(m.JoinAddress)
		copy(dAtA[i:], m.JoinAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JoinAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgJoinDaoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgJoinDaoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgJoinDaoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgMintAndAllocateExp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Member)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgMintAndAllocateExpResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgBurnAndRemoveMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBurnAndRemoveMemberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgJoinDao) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.JoinAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GovAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MaxToken != 0 {
		n += 1 + sovTx(uint64(m.MaxToken))
	}
	return n
}

func (m *MsgJoinDaoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgMintAndAllocateExp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintAndAllocateExp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintAndAllocateExp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Member", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Member = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMintAndAllocateExpResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintAndAllocateExpResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintAndAllocateExpResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBurnAndRemoveMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBurnAndRemoveMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBurnAndRemoveMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBurnAndRemoveMemberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBurnAndRemoveMemberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBurnAndRemoveMemberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgJoinDao) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgJoinDao: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgJoinDao: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JoinAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GovAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GovAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxToken", wireType)
			}
			m.MaxToken = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxToken |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgJoinDaoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgJoinDaoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgJoinDaoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
